vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /resources/images
            upload_destination: '%kernel.project_dir%/public/resources/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_remove: true