vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /resources/images
            upload_destination: '%kernel.project_dir%/public/resources/images'
            namer:
                service: vich_uploader.namer_origname

            delete_on_update: true