vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: '%env(VICH_IMG_DIR)%'
            upload_destination: '%env(VICH_UPLOAD_DESTINATION)%'
            namer:
#                filename wordt vervangen door een unieke id
                service: vich_uploader.namer_uniqid

            delete_on_update: true