vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: "https://wdev2.be/julie21/eindwerk/resources/images"
            upload_destination: "/var/www/html/wdev2.be/web/julie21/eindwerk/resources/images"
            namer:
#                filename wordt vervangen door een unieke id
                service: vich_uploader.namer_uniqid

            delete_on_update: true